package com.csye6225.fall2018.courseservice.datamodel;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Students")
public class Student {
	private String FirstName;
	private String LastName;
	private String id;
	private String StudentId;
	// private Long image;
	private List<String> courseIds;
	private String courseName;
	private String programName;
	private String department;
	private String emailId;

	public Student() {

	}

	public Student(String FirstName, String LastName, String id, String StudentId, String courseName,
			String programName) {

		this.FirstName = FirstName;
		this.LastName = LastName;
		this.id = id;
		this.StudentId = StudentId;
		// this.image = image;
		this.courseName = courseName;
		this.programName = programName;

	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "studentId-index", attributeName = "studentId")
	public String getStudentId() {
		return StudentId;
	}

	public void setStudentId(String studentId) {
		this.StudentId = studentId;
	}

	@DynamoDBAttribute(attributeName = "firstName")
	public String getFirstName() {
		return FirstName;
	}

	public void setFirstName(String firstName) {
		this.FirstName = firstName;
	}
	@DynamoDBAttribute(attributeName="emailId")
 	public String getEmailId() {
 		return emailId;
 	}

 	public void setEmailId(String emailId) {
 		this.emailId = emailId;
 	}
 	
 	@DynamoDBAttribute(attributeName="courseIds")
	public List<String> getCourseIds() {
		return courseIds;
	}

	public void setCourseIds(List<String> courseIds) {
		this.courseIds = courseIds;
	}

	@DynamoDBAttribute(attributeName = "lastName")
	public String getLastName() {
		return LastName;
	}

	public void setLastName(String lastName) {
		this.LastName = lastName;
	}

	//
	// public Long getImage() {
	// return image;
	// }
	//
	// public void setImage(Long image) {
	// this.image = image;
	// }
	@DynamoDBAttribute(attributeName = "courseName")
	public String getCourseName() {
		return courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@DynamoDBAttribute(attributeName = "programName")
	public String getProgramName() {
		return programName;
	}

	public void setProgramName(String programName) {
		this.programName = programName;
	}

	@DynamoDBIgnore
	@Override
	public String toString() {
		return "StudentId=" + getStudentId() + ", firstName=" + getFirstName() + ", courseName=" + getCourseName()
				+ ",getProgramName" + getProgramName();
	}
	


}
